// Constants.swift
// Cube Run: Origins – SpriteKit game constants
// Generated by Claude Code – beginner-friendly definitions

import SpriteKit
import UIKit

/// Centralized game constants.
struct Constants {
    // MARK: - Colors
    /// Player color (bright blue).
    static let playerColor = SKColor(red: 0.0, green: 0.5, blue: 1.0, alpha: 1.0)
    /// Evil cube (enemy) color (vivid red).
    static let evilCubeColor = SKColor(red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0)
    /// Background gradient start color.
    static let backgroundTopColor = SKColor(red: 0.9, green: 0.95, blue: 1.0, alpha: 1.0)
    /// Background gradient end color.
    static let backgroundBottomColor = SKColor(red: 0.6, green: 0.8, blue: 1.0, alpha: 1.0)

    // MARK: - Physics Categories (bit masks)
    /// Bit mask for the player.
    static let playerCategory: UInt32 = 0x1 << 0
    /// Bit mask for obstacles (e.g., walls, spikes).
    static let obstacleCategory: UInt32 = 0x1 << 1
    /// Bit mask for the evil cube (enemy).
    static let evilCubeCategory: UInt32 = 0x1 << 2
    /// Bit mask for the ground.
    static let groundCategory: UInt32 = 0x1 << 3

    // MARK: - Gameplay Speed
    /// Base forward speed of the player (points per second).
    static let baseSpeed: CGFloat = 300.0
    /// Speed multiplier applied when the player reaches the chase threshold.
    static let chaseSpeedMultiplier: CGFloat = 1.5
    /// Maximum speed the player can reach.
    static let maxSpeed: CGFloat = 800.0

    // MARK: - Score & Thresholds
    /// Score at which the evil cube starts chasing the player.
    static let chaseScoreThreshold: Int = 500
    /// How often (in seconds) new obstacles are spawned.
    static let obstacleSpawnInterval: TimeInterval = 2.0
    /// Minimum interval between enemy spawns.
    static let evilCubeSpawnInterval: TimeInterval = 5.0

    // MARK: - Other Magic Numbers
    /// Player jump impulse.
    static let jumpImpulse: CGFloat = 450.0
    /// Gravity applied to the physics world.
    static let gravity: CGVector = CGVector(dx: 0.0, dy: -9.8)
    /// Size of the player sprite (width, height).
    static let playerSize = CGSize(width: 50, height: 50)
    /// Size of the evil cube sprite.
    static let evilCubeSize = CGSize(width: 45, height: 45)
    /// Z‑position values to control rendering order.
    struct ZPosition {
        static let background: CGFloat = -10
        static let ground: CGFloat = 0
        static let obstacle: CGFloat = 5
        static let player: CGFloat = 10
        static let evilCube: CGFloat = 12
        static let ui: CGFloat = 100
    }
    // Enemy constants
    struct Enemy {
        static let size: CGFloat = 45.0
        static let color: SKColor = .red
        // Additional timing constants
        static let introDuration: TimeInterval = 6.0
        static let chaseDuration: TimeInterval = 5.0
    }
}
